### ISSUE TITLE
Graph layout visualization gets stuck sometimes 

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-frontend#11] opened 2018-05-30 14:51 UTC
_From @glciampaglia on May 14, 2018 16:27_

Per title, after launching a few queries without reloading, every now and then the visualization gets stuck on the circular layout.

_Copied from original issue: IUNetSci/hoaxy-botometer#254_

**Comment by mihaivavram** [comment] 2018-06-23 16:46
One way to reproduce this consistently is to query an article that produces a significant amount of nodes, e.g., >800 nodes in the visualization. Such as [this](http://hoaxy.iuni.iu.edu/#query=Inconsolable%20Jeff%20Sessions%20Tries%20To%20Commit%20Suicide%20By%20Smoking%20Joint&sort=relevant&type=Hoaxy) one.

Then do the following:

1) Using the bottom left focus chart, select and drag the rightmost end of the timeline, selecting a chunk at the end of the timeline as below:
![screenshot from 2018-06-23 11-37-14](https://user-images.githubusercontent.com/24797255/41811690-d762915e-76d9-11e8-9820-a863cc669313.png)

2) Quickly extend the left end all the way to the left of the timeline before the focus from step 1 fully renders. Hence step 2 needs to happen in really quick succession after step 1. The timeline focus chart should now look like this:
![screenshot from 2018-06-23 11-44-25](https://user-images.githubusercontent.com/24797255/41811735-cdd0dcda-76da-11e8-8c75-3d5c37bff673.png)

The graph should now freeze in a circle as so:
![screenshot from 2018-06-23 11-45-45](https://user-images.githubusercontent.com/24797255/41811746-0021bec0-76db-11e8-88f2-d8360ccf7201.png)

**Comment by mihaivavram** [comment] 2018-06-24 04:04
The issue above is due to the fact that there is an asynchronous timeout that happens after `2000 + (Math.floor(Math.sqrt(graph.edges.length)) *600)` milliseconds in the draw graph function, which renders the sigma graph.

This asynchronous timeout runs a delayed function which stops the sigma graph from drawing/expanding after that time. This is a nice feature (we don't want the graph to expand forever!); however, one can imagine that if many graphs are launched in quick succession (as in the example in the post above), this timeout will stop sigma from drawing a newly born graph if the timing is right!

This has been fixed by including a semaphore flag which keeps track of how many timeouts have been launched, and only when the most immediate timeout (one for the current new graph) is present, we launch the function to stop the sigma graph. This has been pushed in the deployment branch and seems to be working fine.

Closing for now unless we decide to open again for some reason.

**Closed by mihaivavram** 2018-06-24 04:04 UTC
Labels: Bug, High Priority
